name: Repository Manager
on:
  workflow_dispatch:
  create:
  issues:
    types: [opened, reopened, closed]
  pull_request:
    branches: [main]
    types: [opened, reopened, closed]
  release:
    types: [created, published]

jobs:
  manager:
    name: Repository Manager
    uses: Katsute/Repository-Manager/.github/workflows/manager.yml@main
    secrets:
      token: ${{ secrets.token }}