name: Repository Manager
on:
  workflow_call:
    secrets:
      token:
        required: true
  workflow_dispatch:
  create:
  issues:
    types: [opened, reopened, closed]
  pull_request:
    branches: [main]
    types: [opened, reopened, closed]
  release:
    types: [created, published]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}

      - name: Print Debug
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.token }}
          script: core.info(require("util").inspect(context, true, 6));

  issue:
    name: Issue Locking
    runs-on: ubuntu-latest
    if: github.event_name == "issues"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}

      - name: Issue Lock
        env:
          ISSUE: ${{ github.event.issue && 'issue' || 'pr' }}
          NUMBER: ${{ github.event.issue && github.event.issue.number || github.event.pull_request.number }}
          LOCK: ${{ github.event.action == 'closed' && 'lock' || 'unlock' }}
        run: gh $ISSUE $LOCK $NUMBER