name: Repository Manager
on:
  workflow_call:
    inputs:
      login:
        type: string
        required: true
      username:
        type: string
        required: true
      email:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    if: github.repository == 'Katsute/Repository-Manager'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}

      - name: Print Debug
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.token }}
          script: core.info(require("util").inspect(context, true, 6));

  comment:
    name: Commands
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && contains('OWNER, MEMBER, COLLABORATOR', github.event.comment.author_association)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}

      - name: Parse Comment
        uses: actions/github-script@v6
        env:
          login: ${{ inputs.login }}
          comment: ${{ github.event.comment.body }}
        with:
          github-token: ${{ secrets.token }}
          script: |
            const login = process.env.login;
            const comment = process.env.comment;

            if(comment.startsWith(`@${login}`)){
              const parts = comment.split(' ').slice(1);
              core.exportVariable("command", parts[0].toLowerCase());
              core.exportVariable("args", parts.slice(1).join(' '));
              core.exportVariable("argsnh", parts.slice(1).join(' ').replace(/#/g, ''));
            }

      - name: Create Issue
        if: env.command == 'issue'
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          ACTOR: ${{ github.event.sender.login }}
          NUMBER: ${{ github.event.issue.number }}
          TITLE: ${{ env.args }}
          ISSUE: ${{ github.event.issue && 'issue' || 'pr' }}
        run: |
          link=$(gh issue create -t "$TITLE" -b  "")
          number=${link##*/}

          gh $ISSUE comment $NUMBER -b "@$ACTOR created a new issue at [#$number]($link)"

      - name: Dispatch Workflow
        if: (env.command == 'dispatch' || env.command == 'workflow') && !github.event.issue.pull_request && env.args
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          ACTOR: ${{ github.event.sender.login }}
          NUMBER: ${{ github.event.issue.number }}
          WORKFLOW: ${{ env.args }}
          REF: ${{ github.event.repository.default_branch }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue && 'issue' || 'pr' }}
        run: |
          gh workflow run $WORKFLOW

          gh $ISSUE comment $NUMBER -b "@$ACTOR dispatched workflow [${WORKFLOW}](https://github.com/${REPO}/actions/workflows/${WORKFLOW}) on branch '$REF'"

      - name: Dispatch Workflow (pull)
        if: (env.command == 'dispatch' || env.command == 'workflow') && github.event.issue.pull_request && env.args
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          ACTOR: ${{ github.event.sender.login }}
          NUMBER: ${{ github.event.issue.number }}
          WORKFLOW: ${{ env.args }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue && 'issue' || 'pr' }}
        run: |
          REF=$(gh pr view $NUMBER --json headRefName --jq ".headRefName")

          gh workflow run $WORKFLOW --ref $REF

          gh $ISSUE comment $NUMBER -b "@$ACTOR dispatched workflow [${WORKFLOW}](https://github.com/${REPO}/actions/workflows/${WORKFLOW}) on branch '$REF'"

      - name: Duplicate PR
        if: (env.command == 'pr' || env.command == 'pull') && github.event.issue.pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          ACTOR: ${{ github.event.sender.login }}
          NUMBER: ${{ github.event.issue.number }}
          TITLE: ${{ env.args || github.event.issue.title }}
          name: ${{ inputs.username }}
          email: ${{ inputs.email }}
        run: |
          REF=$(gh pr view $NUMBER --json headRefName --jq ".headRefName")
          SHA=$(gh pr view $NUMBER --json headRefOid --jq ".headRefOid")
          PSHA=${SHA:0:7}
          BRANCH="pr#$NUMBER@$PSHA"

          git config --global user.name "$name"
          git config --global user.email "$email"

          git fetch --all
          git checkout -b "$BRANCH" "origin/$REF"
          git push origin HEAD

          link=$(gh pr create -t "$TITLE" -b "" --head "$BRANCH")
          number=${link##*/}

          gh pr comment $NUMBER -b "@$ACTOR created a new pull request at [#$number]($link)"

      - name: Merge PR
        if: env.command == 'merge' && github.event.issue.pull_request && env.args
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          ACTOR: ${{ github.event.sender.login }}
          NUMBER: ${{ github.event.issue.number }}
          PULL: ${{ env.argsnh }}
          name: ${{ inputs.username }}
          email: ${{ inputs.email }}
        run: |
          FROM=$(gh pr view $NUMBER --json headRefName --jq ".headRefName")
          DEST=$(gh pr view $PULL --json headRefName --jq ".headRefName")
          URL=$(gh pr view $PULL --json url --jq ".url")

          git config --global user.name "$name"
          git config --global user.email "$email"

          git fetch --all
          git checkout "$DEST"
          git merge --squash "origin/$FROM"
          git push origin HEAD

          gh pr comment $NUMBER -b "@$ACTOR merged this pull request into [#$PULL]($URL)"

      - name: Merge Master
        if: (env.command == 'sync' || env.command == 'update') && github.event.issue.pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          ACTOR: ${{ github.event.sender.login }}
          NUMBER: ${{ github.event.issue.number }}
          MASTER: ${{ github.event.repository.default_branch }}
          name: ${{ inputs.username }}
          email: ${{ inputs.email }}
        run: |
          BRANCH=$(gh pr view $NUMBER --json headRefName --jq ".headRefName")

          git config --global user.name "$name"
          git config --global user.email "$email"

          git fetch --all
          git checkout "$BRANCH"
          git merge --no-ff "$MASTER"
          git push origin $BRANCH

      - name: Push Empty Commit
        if: env.command == 'push' && github.event.issue.pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          ACTOR: ${{ github.event.sender.login }}
          NUMBER: ${{ github.event.issue.number }}
          name: ${{ inputs.username }}
          email: ${{ inputs.email }}
        run: |
          BRANCH=$(gh pr view $NUMBER --json headRefName --jq ".headRefName")

          git config --global user.name "$name"
          git config --global user.email "$email"

          git fetch --all
          git checkout "$BRANCH"
          git commit --allow-empty -m "Empty commit"
          git push origin HEAD

      - name: Review PR (approve)
        if: env.command == 'approve' && github.event.issue.pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          ACTOR: ${{ github.event.sender.login }}
          NUMBER: ${{ github.event.issue.number }}
          MESSAGE: ${{ env.args }}
        run: gh pr review $NUMBER --approve --body "Approved by @$ACTOR $MESSAGE"

      - name: Review PR (reject)
        if: env.command == 'reject' && github.event.issue.pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          ACTOR: ${{ github.event.sender.login }}
          NUMBER: ${{ github.event.issue.number }}
          MESSAGE: ${{ env.args }}
        run: gh pr review $NUMBER --request-changes --body "Rejected by @$ACTOR $MESSAGE"

  create:
    name: Branch Rename
    runs-on: ubuntu-latest
    if: github.event_name == 'create' && github.ref_type == 'branch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}

      - name: Create SHA Branch
        if: endsWith(github.event.ref, '@')
        env:
          REF: ${{ github.event.ref }}
          SHA: ${{ github.sha }}
          name: ${{ inputs.username }}
          email: ${{ inputs.email }}
        run: |
          psha=${SHA:0:7}
          branch="$REF$psha"

          git config --global user.name "$name"
          git config --global user.email "$email"

          git checkout -b "$branch"
          git push origin HEAD

          git push origin --delete $REF

      - name: Create Orphan Branch
        if: startsWith(github.event.ref, '!')
        env:
          REF: ${{ github.event.ref }}
          name: ${{ inputs.username }}
          email: ${{ inputs.email }}
        run: |
          branch=${REF:1}

          git config --global user.name "$name"
          git config --global user.email "$email"

          git checkout --orphan "$branch"
          git rm -rf .
          git commit --allow-empty -m "Initial commit"
          git push origin HEAD

          git push origin --delete $REF

  issue:
    name: Issue Locking
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}

      - name: Issue Lock
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          ISSUE: ${{ github.event.issue && 'issue' || 'pr' }}
          NUMBER: ${{ github.event.issue && github.event.issue.number || github.event.pull_request.number }}
          LOCK: ${{ github.event.action == 'closed' && 'lock' || 'unlock' }}
        run: gh $ISSUE $LOCK $NUMBER

  label:
    name: Label Sync
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.repository != 'Katsute/Repository-Manager'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}

      - name: Sync Labels
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          REPO: ${{ github.repository }}
        run: gh label clone Katsute/Repository-Manager --repo $REPO -f